### ISSUE TITLE
Dell Laptop internal touchscreen not recognised

### ISSUE THREAD

**Issue by ceecrb1** [ksandom/niceTouch#1] opened 2023-09-06 09:46 UTC
I left a comment on your youtube video.
The correct device to use for the internal touchcreen is #11 "Wacom HID 8CA Pen stylus", I've managed to make this work manually but REALLY don't want to be doing this manually every time.

Many thanks in advance!!!

Here is my terminal output:

ceecrb1@ceecrb1-Latitude-7389:~$ nt
/usr/local/lib/python3.8/dist-packages/niceTouch/state.py:38: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  this.state = yaml.load(stream)
Touch panel 23 found, but no matching screen was found. Be sure to plug in the screen first.
Screen "Wacom HID 48CA Pen stylus" does not appear to have an associated touch panel. Won't calibrate.
Screen "Wacom HID 48CA Finger touch" does not appear to have an associated touch panel. Won't calibrate.
Screen "Wacom HID 48CA Pen eraser" does not appear to have an associated touch panel. Won't calibrate.
Screen "wch.cn TouchScreen" does not appear to have an associated touch panel. Won't calibrate.
Screen "wch.cn TouchScreen" does not appear to have an associated touch panel. Won't calibrate.
Touch screen "wch.cn TouchScreen" does not appear to be plugged in. Won't calibrate.
Screen "Wacom HID 48CA Pen stylus" does not appear to have an associated touch panel. Won't calibrate.
Screen "Wacom HID 48CA Finger touch" does not appear to have an associated touch panel. Won't calibrate.
Screen "Wacom HID 48CA Pen stylus" does not appear to have an associated touch panel. Won't calibrate.
Screen "Wacom HID 48CA Finger touch" does not appear to have an associated touch panel. Won't calibrate.
Screen "Wacom HID 48CA Pen eraser" does not appear to have an associated touch panel. Won't calibrate.
Screen "Wacom HID 48CA Pen eraser" does not appear to have an associated touch panel. Won't calibrate.
Screen "wch.cn TouchScreen" does not appear to have an associated touch panel. Won't calibrate.
Screen "Wacom HID 48CA Pen eraser" does not appear to have an associated touch panel. Won't calibrate.
Touch screen "wch.cn TouchScreen" does not appear to be plugged in. Won't calibrate.
ceecrb1@ceecrb1-Latitude-7389:~$ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Wacom HID 48CA Pen stylus               	id=11	[slave  pointer  (2)]
⎜   ↳ Wacom HID 48CA Finger touch             	id=12	[slave  pointer  (2)]
⎜   ↳ PS/2 Generic Mouse                      	id=20	[slave  pointer  (2)]
⎜   ↳ Wacom HID 48CA Pen eraser               	id=21	[slave  pointer  (2)]
⎜   ↳ DELL08AF:00 044E:1225 Mouse             	id=13	[slave  pointer  (2)]
⎜   ↳ DELL08AF:00 044E:1225 Touchpad          	id=14	[slave  pointer  (2)]
⎜   ↳ wch.cn TouchScreen                      	id=22	[slave  pointer  (2)]
⎜   ↳ wch.cn TouchScreen                      	id=23	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Intel HID events                        	id=16	[slave  keyboard (3)]
    ↳ Intel HID 5 button array                	id=17	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=19	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD: Integrate         	id=10	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD: Integrate         	id=9	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=18	[slave  keyboard (3)]
    ↳ DELL08AF:00 044E:1225 UNKNOWN           	id=15	[slave  keyboard (3)]
ceecrb1@ceecrb1-Latitude-7389:~$

**Comment by ksandom** [comment] 2023-09-07 10:30
Hi @ceecrb1 ,

Thanks for posting. 

Let's quickly try starting from fresh to see if we can see where the problem is coming from:

1. `mv -v ~/.config/niceTouch.yaml ~/.config/niceTouch.yaml.backup`
    * Please provide the terminal output for this step.
2. Unplug all external monitors and touch panels.
3. Run `nt`
    * Please provide the terminal output for this step. And comment that it's from this step.
4. At this point the integrated touch panel should be working correctly. Test.
5. Plug in the screen that has the touch panel.
6. Run `nt`
    * Please provide the terminal output for this step. And comment that it's from this step.
7. Plug in the touch panel that goes with the screen that you just plugged in.
8. Run `nt`
    * Please provide the terminal output for this step. And comment that it's from this step.
9. At this point both touch panels should be working correctly. Test.
10. Plug in all remaining screens.
11. Run `nt`
    * Please provide the terminal output for this step. And comment that it's from this step.
12. Please provide the contents of `~/.config/niceTouch.yaml`

Additionally: If it doesn't work. Please let me know which step things didn't match up in.

Edit: Added step 11 to make sure that the niceTouch.yaml is in its final state.

**Comment by ksandom** [comment] 2023-09-12 09:14
Any luck?

**Comment by ceecrb1** [comment] 2023-09-14 10:52
> Any luck?

Sorry, not had a chance to look yet, a crazy week. Also currently this project is on hold as there is a more urgent issue I discovered in the system which may force me back to windows. (This is professional lighting desk system, a new model where the physical signal used which is it's entire reason to exist, is not actually outputting with on linux)

**Comment by ksandom** [comment] 2023-09-16 21:02
No worries. Take your time.

\[Edit: Removed a whole heap of irrelevant stuff relating to another project that I'm also answering questions about. Sorry about that.\]

I'll check back in a while if I haven't heard from you to see if you're still needing help.

**Comment by ksandom** [comment] 2023-10-13 11:13
I'm going to close this for now. But definitely re-open and comment if you'd like to pick it up again. I hope that you've been able to get your system working.

**Closed as completed by ksandom** 2023-10-13 11:13 UTC
